### ISSUE TITLE
Error with gtsummary 2.0.0

### ISSUE THREAD

**Issue by FDUguchunhui** [zheer-kejlberg/Z.gtsummary.addons#5]
Hi Dr. Al-Mashhadi: 
thank you for this nice addon feature for gtsummary. I just find it doesn't work for the new gtsummary version 2.0.0. After switch to 1.7.2 it works fine. It will nice if you can look into the problem and fix it.

```
> trial %>% 
+     tbl_summary(by = grade, include = c(age, stage)) %>%
+     add_SMD(location = "level")
```
There was a error for variable "age"
✖ argument is of length zero
There was a error for variable "stage"
✖ argument is of length zero
Error in `gtsummary::add_stat()`:
! Dimension of "age" and the added statistic do not match.
ℹ Expecting statistic/data frame to be length/no. rows 0.

**Comment by zheer-kejlberg** [comment]
Hi Chunhui Gu
Sorry for my late response - I've been unable to look into this for the past few months. 
However, it's top priority now. I can see that {gtsummary} was completely rewritten with v2, so I'll have to do some digging to find out what exactly is being handled differently.

At some point, this package could also use a rewrite from scratch (to lose dependencies), but for now I'll try to patch it asap!

**Comment by zheer-kejlberg** [comment]
Hello again

Finally got it all working with the new gtsummary package. Sorry for the inconvenience!
